spring:
  application:
    name: gateway-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

    gateway:
#      discovery:
#        locator:
#          enabled: true # accept name mapping with server name
      routes:
      - id: account-route
        uri: lb://account-service
        predicates: Path=/account-service/**
        filters:
          - StripPrefix=1


      - id: statistic-route
        uri: lb://statistic-service
        predicates: Path=/statistic-service/**
        filters:
          - StripPrefix=1


