server:
  port: 8080
  servlet:
    context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://${DBMS_HOST:127.0.1.1}:5432/postgres
    username: ${DBMS_USERNAME:hieutm}
    password: ${DBMS_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  circuitbreaker:
    config:
      default: 10
  timelimiter:
    configs:
      default:
        timeoutDuration: 1s
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      micrometer:
        enabled: true
      oauth2:
        enabled: false # false: app using config java # true: openfein auto config
        # indicate client registration for all
        clientRegistrationId: notification-service
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:9000
            # use service id for registry (recommendation)
        registration:
          statistic-service:
            authorizationGrantType: client_credentials
            clientId: accountservice
            clientSecret: 123
            scope: logs
            provider: spring
          notification-service:
            authorizationGrantType: client_credentials
            clientId: accountservice
            clientSecret: 123
            scope: notification
            provider: spring
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security:
          oauth2: DEBUG
          jwt: DEBUG
        web:
          client:
            RestTemplate: DEBUG
  file:
    name: log/account/myapp.log
