server:
  port: 9999
  servlet:
    context-path: /

spring:
  mail:
    default-encoding: UTF-8
    host: diemdungodau2502@gmail.com
    #Create your app password with other (custom name)
    #https://myaccount.google.com/u/1/apppasswords
    username: app-test
    password: "bamwoovtcxbwacol"
    port: 587
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
  boot:
    admin:
      notify:
        mail:
          enabled: true
          to: hieutranminhbk@gmail.com
